; 共通設定
upload_max_filesize = 50M
post_max_size = 60M
max_execution_time = 300
max_input_time = 180
memory_limit = 256M
file_uploads = On
allow_url_include = Off
enable_dl = Off
expose_php = Off

; 開発環境のみ
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /proc/self/fd/2

; 本番環境のみ
; display_errors = Off
; display_startup_errors = Off
; error_reporting = E_ALL
; log_errors = On
